from howfsc.control.cs import ControlStrategy
from howfsc.model.mode import CoronagraphMode
from howfsc.util.loadyaml import loadyaml

from corgihowfsc.utils.corgisim_gitl_frames import GitlImage
from corgihowfsc.utils.gitl_worker import _get_image_worker, _jac_worker


def _apply_hconf_overrides(hconf, worker_config):
    """Apply any user-specified stellar overrides onto a loaded hconf dict."""
    if worker_config.get('stellar_vmag') is not None:
        hconf['star']['stellar_vmag'] = worker_config['stellar_vmag']
    if worker_config.get('stellar_type') is not None:
        hconf['star']['stellar_type'] = worker_config['stellar_type']
    if worker_config.get('stellar_vmag_target') is not None:
        hconf['star']['stellar_vmag_target'] = worker_config['stellar_vmag_target']
    if worker_config.get('stellar_type_target') is not None:
        hconf['star']['stellar_type_target'] = worker_config['stellar_type_target']


def initialize_mpi_worker_state(worker_config):
    """
    Build persistent worker-local state once per MPI rank.
    Initialize the persistent state for a single MPI worker rank.

    This function reconstructs the worker local objects from the serializable
    configuration dictionary received during the initial ``INIT`` step. The
    returned state is reused for later frame and Jacobian tasks on that worker.

    Args:
        worker_config : dict, Dictionary containing the information needed to reconstruct the worker local objects.

    Returns:
        dict: Persistent worker state containing ``'cfg'``, ``'hconf'``,
        ``'cstrat'``, and ``'imager'``.
    """

    cfg = CoronagraphMode(worker_config['cfgfile'])
    hconf = loadyaml(worker_config['hconffile'], custom_exception=TypeError)
    _apply_hconf_overrides(hconf, worker_config)
    cstrat = ControlStrategy(worker_config['cstratfile'])
    
    imager = GitlImage(
        cfg=cfg,
        cstrat=cstrat,
        hconf=hconf,
        backend=worker_config['backend_type'],
        cor=worker_config['mode'],
        corgi_overrides=worker_config['corgi_overrides'],
    )
    return {
        'cfg': cfg,
        'hconf': hconf,
        'cstrat': cstrat,
        'imager': imager,
    }


def run_mpi_frame_task(worker_state, task):
    """
    Execute a single frame task inside a MPI worker.

    ``worker_state`` contains the worker-local objects initialized once during the
    ``INIT`` step, while ``task`` contains the per-frame inputs sent by rank 0.

    This function combines the cached worker state with the lightweight task
    parameters and forwards them to ``_get_image_worker`` for frame generation. 

    Args:
        worker_state : dict, Persistent worker state containing ``'cfg'``, ``'hconf'``, ``'cstrat'``, and ``'imager'`` 
        for frame generation.

        task : dict, Dictionary containing the per-frame parameters needed for frame generation, including:
            - 'dm1v', 'dm2v': DM settings for the frame.
            - 'exptime': Exposure time for the frame.
            - 'gain': Camera gain setting for the frame.
            - 'nframes': Number of frames to generate for this setting.
            - 'crop': Crop settings for the frame.
            - 'lind': Index of the wavelength in the probing sequence.
            - 'peakflux': Pre-computed peak flux for the wavelength.
            - 'fracbadpix': Fraction of additional random bad pixels to inject.
            - 'seed_offset': Integer offset to ensure different random seeds across frames.
    
    Returns:
        np.ndarray: Simulated detector frame generated by the imager for the given parameters.
    """
    return _get_image_worker(
        worker_state['imager'],
        task['dm1v'],
        task['dm2v'],
        task['exptime'],
        task['gain'],
        task['nframes'],
        task['crop'],
        task['lind'],
        task['peakflux'],
        worker_state['cstrat'].fixedbp,
        task['fracbadpix'],
        task['seed_offset']
        )


def run_mpi_jac_task(worker_state, task):
    """
    Execute a Jacobian chunk task inside a MPI worker.

    ``worker_state`` contains the worker-local objects initialized once during the ``INIT`` step, while ``task`` contains the per-chunk inputs sent by rank 0. This function combines the cached worker state with the lightweight task parameters and forwards them to ``_jac_worker`` for Jacobian chunk computation.

    Args:
        worker_state : dict, Persistent worker state containing ``'cfg'``, ``'hconf'``, ``'cstrat'``, and ``'imager'`` for Jacobian computation.

        task : dict, Dictionary containing the per-chunk parameters needed for Jacobian computation, including:
            - 'ijproc': Tuple of (indj, indk) indices specifying the wavelength and DM setting for this chunk.
            - 'dmset_list': List of DM settings for the probing sequence.
            - 'jacmethod': Method to use for Jacobian computation (e.g., 'fd' for finite difference).
            - 'num_threads': Number of threads to use for this computation.
    
    Returns:
        tuple: ``(ijproc, partial_jac)`` as returned by ``_jac_worker``, 
                where ``partial_jac`` has shape ``(2, len(ijproc), ndhpix)``.    
    """
    return _jac_worker(
        worker_state['cfg'],
        task['ijproc'],
        task['dmset_list'],
        task['jacmethod'],
        task['num_threads'],
    )
